# Generated by Django 6.0.2 on 2026-03-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitacao', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa')], max_length=10)),
                ('instituicao', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('periodo', models.CharField(max_length=50)),
                ('finalidade', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('anexo_edocs', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='agenda.ambiente')),
            ],
        ),
    ]
