# Generated by Django 6.0.2 on 2026-03-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='finalidade',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='periodo',
            field=models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=10),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['ambiente', 'data_inicio', 'data_fim'], name='agenda_rese_ambient_55c0fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('ambiente', 'data_inicio', 'data_fim', 'periodo'), name='reserva_unica_por_periodo'),
        ),
    ]
