# Generated by Django 6.0.2 on 2026-03-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_reserva_finalidade_alter_reserva_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='periodo',
            field=models.CharField(choices=[('INTEGRAL', 'Integral'), ('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=50),
        ),
    ]
